package com.black.elvis1615.hola1.graficar;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 04 17:45:37 CST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int rojo = 16;
  public static final int poligono = 13;
  public static final int morado = 20;
  public static final int circulo = 10;
  public static final int coma = 8;
  public static final int numero = 23;
  public static final int por = 4;
  public static final int negro = 22;
  public static final int linea = 14;
  public static final int azul = 15;
  public static final int menos = 3;
  public static final int div = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int cuadrado = 11;
  public static final int verde = 17;
  public static final int graficar = 9;
  public static final int rectangulo = 12;
  public static final int amarillo = 18;
  public static final int mas = 2;
  public static final int naranja = 19;
  public static final int ParC = 7;
  public static final int cafe = 21;
  public static final int ParA = 6;
}

